# Generated by Django 5.2.17 on 2026-08-05 06:41
#
# EDITED (post-hoc): every CreateModel below originally had 'managed': False,
# meaning Django never actually ran the CREATE TABLE DDL for any of these 31
# tables -- they only exist today because the database was provisioned
# externally (legacy pre-Django schema). Migrations 0008/0009/0014 later
# flipped 'managed' to True via AlterModelOptions (a state-only change, no
# DDL), which let the ORM read/write them, but nothing had ever created them
# for a genuinely fresh database: `python manage.py migrate` from empty
# failed the moment migration 0006 tried to ALTER a tds_inputs table that
# was never created. Flipping 'managed' to True here too makes this
# migration actually create these tables — the fields listed are exactly
# what these tables looked like at this point in history (before 0002-0021's
# real incremental AddField/RunSQL changes layer on top, as they always
# did), so a fresh database now replays the exact same schema evolution
# production went through instead of stalling on a missing table.
#
# SAFE for every environment that already has this migration recorded as
# applied (local dev, production) — Django never re-runs an applied
# migration, so this change is inert there; it only takes effect the first
# time `migrate` runs against a database that doesn't have these tables yet.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeltRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_name', models.TextField()),
            ],
            options={
                'db_table': 'belt_ratings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BeltRatingValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_value', models.TextField(blank=True, null=True)),
                ('indus_value', models.TextField()),
            ],
            options={
                'db_table': 'belt_rating_values',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BeltType',
            fields=[
                ('belt_id', models.AutoField(primary_key=True, serialize=False)),
                ('belt_type', models.TextField()),
            ],
            options={
                'db_table': 'belt_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IndusBrand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.TextField()),
            ],
            options={
                'db_table': 'brands',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConstructionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_name', models.TextField(unique=True)),
                ('max_belt_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('qty_label', models.TextField(default='Rolls')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'construction_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('max_height_m', models.DecimalField(decimal_places=3, max_digits=5)),
                ('max_width_m', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            options={
                'db_table': 'container_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoverGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_code', models.TextField()),
                ('grade_description', models.TextField(blank=True, null=True)),
                ('specific_gravity', models.FloatField()),
            ],
            options={
                'db_table': 'cover_grades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoverGradeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_value', models.TextField(blank=True, null=True)),
                ('indus_value', models.TextField()),
            ],
            options={
                'db_table': 'cover_grade_values',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('contact_person', models.TextField(blank=True, null=True)),
                ('application', models.TextField(blank=True, null=True)),
                ('plant_location', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DimensionalParameterSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('tolerance_value', models.TextField()),
            ],
            options={
                'db_table': 'dimensional_parameter_specs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FabricStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.TextField()),
            ],
            options={
                'db_table': 'fabric_styles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FabricStyleParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_value', models.TextField(blank=True, null=True)),
                ('indus_value', models.TextField()),
            ],
            options={
                'db_table': 'fabric_style_parameter_values',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_code', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('manufacturer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fabric_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FabricTypeParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_value', models.TextField(blank=True, null=True)),
                ('indus_value', models.TextField()),
            ],
            options={
                'db_table': 'fabric_type_parameter_values',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HotSpliceCuringLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_belt_thickness_mm', models.IntegerField(unique=True)),
                ('specific_pressure', models.TextField()),
                ('curing_temp', models.TextField()),
                ('curing_time_min', models.IntegerField()),
                ('cooling_temp_c', models.IntegerField()),
            ],
            options={
                'db_table': 'hot_splice_curing_lookup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PackingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_name', models.TextField(unique=True)),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'packing_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('purpose_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose_type', models.TextField()),
            ],
            options={
                'db_table': 'purposes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reel_name', models.TextField(unique=True)),
                ('formula_key', models.TextField()),
                ('num_rolls_base', models.IntegerField()),
                ('core_diameter_m', models.DecimalField(decimal_places=4, max_digits=6)),
                ('center_to_center_m', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('max_roll_diameter_m', models.DecimalField(decimal_places=2, default='2.50', max_digits=4)),
            ],
            options={
                'db_table': 'reel_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegionContainerWeightLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('max_gross_weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'region_container_weight_limits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SamplingPlanLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_belt_length_m', models.DecimalField(decimal_places=2, max_digits=12, unique=True)),
                ('sample_count', models.IntegerField()),
                ('standard_ref', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sampling_plan_lookup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpliceMethodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulcanization_method', models.TextField(unique=True)),
                ('buffer_mm', models.IntegerField()),
                ('standard_ref', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'splice_method_config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpliceStepLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_fabric_rating_kn_m', models.IntegerField(unique=True)),
                ('step_length_mm', models.IntegerField()),
                ('standard_ref', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'splice_step_lookup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('standard_id', models.AutoField(primary_key=True, serialize=False)),
                ('standard_name', models.TextField()),
                ('standard_edition', models.TextField(blank=True, null=True)),
                ('standard_description', models.TextField(blank=True, null=True)),
                ('standard_country', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'standards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StandardTestMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.TextField(blank=True, null=True)),
                ('test_method', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'standard_test_methods',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TDSInput',
            fields=[
                ('tds_id', models.AutoField(primary_key=True, serialize=False)),
                ('tds_number', models.TextField(unique=True)),
                ('tds_doc_number', models.TextField(blank=True, null=True)),
                ('tds_date', models.DateField()),
                ('status', models.TextField(default='draft')),
                ('construction_type', models.TextField(default='Open-End')),
                ('belt_description', models.TextField(blank=True, null=True)),
                ('belt_length_m', models.DecimalField(decimal_places=3, max_digits=10)),
                ('belt_weight_per_m_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('make_of_fabric', models.TextField(default='MIT')),
                ('belt_width_mm', models.IntegerField()),
                ('num_plies', models.IntegerField()),
                ('top_cover_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bottom_cover_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carcass_from_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carcass_thickness_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interply_skim_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_thickness_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('breaker_top', models.BooleanField(default=False)),
                ('breaker_top_plies', models.IntegerField(blank=True, null=True)),
                ('breaker_bottom', models.BooleanField(default=False)),
                ('breaker_bottom_plies', models.IntegerField(blank=True, null=True)),
                ('edge_construction', models.TextField()),
                ('num_rolls', models.IntegerField(blank=True, null=True)),
                ('length_per_roll_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('roll_dimensions', models.TextField(blank=True, null=True)),
                ('net_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_weight_per_roll_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_region', models.TextField(blank=True, null=True)),
                ('splicing_required', models.BooleanField(default=False)),
                ('vulcanization_method', models.TextField(blank=True, null=True)),
                ('num_joints', models.IntegerField(blank=True, null=True)),
                ('step_length_mm', models.IntegerField(blank=True, null=True)),
                ('splice_length_mm', models.IntegerField(blank=True, null=True)),
                ('total_extra_length_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tds_inputs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TDSParameter',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_group', models.TextField()),
                ('parameter_name', models.TextField()),
                ('display_order', models.IntegerField()),
                ('is_user_input', models.BooleanField(default=False)),
                ('visibility_condition', models.TextField(blank=True, null=True)),
                ('spec_equals_indus', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tds_parameters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TDSSequence',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('last_number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tds_sequence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TDSUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('password_hash', models.TextField()),
                ('full_name', models.TextField(blank=True, null=True)),
                ('role', models.TextField(default='tds_creator')),
                ('designation', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BrandBeltType',
            fields=[
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='belt_type_links', serialize=False, to='core.indusbrand')),
            ],
            options={
                'db_table': 'brand_belt_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BrandParameter',
            fields=[
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='brand_parameters', serialize=False, to='core.indusbrand')),
                ('display_order', models.IntegerField()),
                ('is_user_input', models.BooleanField(default=False)),
                ('visibility_condition', models.TextField(blank=True, null=True)),
                ('spec_equals_indus', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'brand_parameters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PurposeBeltType',
            fields=[
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='belt_type_links', serialize=False, to='core.purpose')),
            ],
            options={
                'db_table': 'purpose_belt_type',
                'managed': True,
            },
        ),
    ]
