# Generated by Django 5.2.17 on 2026-08-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTOTP',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=64)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_totp',
                'managed': True,
            },
        ),
    ]
