# Generated by Django 5.2.17 on 2026-08-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tds_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
