# Generated by Django 5.2.17 on 2026-08-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_trusteddevice_device_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beltrating',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='beltratingvalue',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='belttype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='constructiontype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='containertype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='covergrade',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='covergradevalue',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dimensionalparameterspec',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fabricstyle',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fabricstyleparametervalue',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fabrictype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fabrictypeparametervalue',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hotsplicecuringlookup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='indusbrand',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='packingtype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='purpose',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reeltype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='regioncontainerweightlimit',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='samplingplanlookup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='splicemethodconfig',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='splicesteplookup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='standardtestmethod',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tdsinput',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tdsparameter',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tdssequence',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tdsuser',
            options={'managed': True},
        ),
    ]
