# Generated by Django 5.2.17 on 2026-08-24 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_beltrating_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beltrating',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='beltratingvalue',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='belttype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='constructiontype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='containertype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='covergrade',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='covergradevalue',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dimensionalparameterspec',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fabricstyle',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fabricstyleparametervalue',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fabrictype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fabrictypeparametervalue',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hotsplicecuringlookup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='indusbrand',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='packingtype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='purpose',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reeltype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='regioncontainerweightlimit',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='samplingplanlookup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='splicemethodconfig',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='splicesteplookup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='standardtestmethod',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tdsinput',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tdsparameter',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tdssequence',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tdsuser',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='TDSAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('approve', 'Approve'), ('decline', 'Decline'), ('delete', 'Delete'), ('packing_recompute', 'Packing Recompute'), ('batch_create', 'Batch Create'), ('download_pdf', 'Download PDF')], db_index=True, max_length=32)),
                ('tds_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('tds_number', models.CharField(blank=True, max_length=20)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tds_audit_log',
                'ordering': ['-timestamp'],
                'managed': True,
                'indexes': [models.Index(fields=['tds_id', 'timestamp'], name='tds_audit_l_tds_id_e7579e_idx'), models.Index(fields=['actor_id', 'timestamp'], name='tds_audit_l_actor_i_dcf232_idx')],
            },
        ),
    ]
