# Generated by Django 5.2.17 on 2026-08-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_qapitem_record_mark'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='qapsection',
            name='unique_template_section_code',
        ),
        migrations.AlterField(
            model_name='qapitem',
            name='characteristic',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='qapitem',
            name='component',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='qapitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qapitem',
            name='record_mark',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='qapitem',
            name='type_of_check',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='qaprecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qapsection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qaptemplate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tdsauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('approve', 'Approve'), ('decline', 'Decline'), ('delete', 'Delete'), ('packing_recompute', 'Packing Recompute'), ('batch_create', 'Batch Create'), ('download_pdf', 'Download PDF'), ('login', 'Login'), ('logout', 'Logout')], db_index=True, max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='qapsection',
            unique_together={('template', 'section_code')},
        ),
        migrations.AlterModelTable(
            name='belttype',
            table='belt_types',
        ),
        migrations.AlterModelTable(
            name='indusbrand',
            table='brands',
        ),
        migrations.AlterModelTable(
            name='purpose',
            table='purposes',
        ),
    ]
