# Generated by Django 5.2.17 on 2026-08-27 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_beltrating_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beltrating',
            name='fabric_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='belt_ratings', to='core.fabrictype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beltratingvalue',
            name='belt_rating',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.beltrating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beltratingvalue',
            name='parameter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='belt_rating_values', to='core.tdsparameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandbelttype',
            name='belt_type',
            field=models.ForeignKey(db_column='belt_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='brand_links', to='core.belttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandparameter',
            name='parameter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='brand_parameters', to='core.tdsparameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covergrade',
            name='standard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='cover_grades', to='core.standard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covergradevalue',
            name='cover_grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.covergrade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covergradevalue',
            name='parameter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cover_grade_values', to='core.tdsparameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimensionalparameterspec',
            name='parameter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dimensional_specs', to='core.tdsparameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimensionalparameterspec',
            name='standard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dimensional_specs', to='core.standard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricstyle',
            name='fabric_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='core.fabrictype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricstyleparametervalue',
            name='fabric_style',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.fabricstyle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricstyleparametervalue',
            name='parameter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fabric_style_values', to='core.tdsparameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabrictypeparametervalue',
            name='fabric_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.fabrictype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabrictypeparametervalue',
            name='parameter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fabric_type_values', to='core.tdsparameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purposebelttype',
            name='belt_type',
            field=models.ForeignKey(db_column='belt_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='purpose_links', to='core.belttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regioncontainerweightlimit',
            name='container_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='weight_limits', to='core.containertype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='standards', to='core.indusbrand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardtestmethod',
            name='parameter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='test_methods', to='core.tdsparameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardtestmethod',
            name='standard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='test_methods', to='core.standard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tds', to='core.tdsuser'),
        ),
        # SeparateDatabaseAndState (fixed): the physical batch_id column was
        # already added by 0006_tds_batch's own RunSQL (`ADD COLUMN IF NOT
        # EXISTS batch_id ...`, which runs unconditionally regardless of
        # managed status) — a plain AddField here re-adds the same column for
        # real (tdsinput was managed=True again by this point, so AddField is
        # not a no-op) and fails with "column already exists" on any replay
        # from a fresh database. Django's own state just needs to learn about
        # the `batch` FK field; no new database column is needed.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='tdsinput',
                    name='batch',
                    field=models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_records', to='core.tdsbatch'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='belt_rating',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tds_inputs', to='core.beltrating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='belt_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tds_inputs', to='core.belttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tds_inputs', to='core.indusbrand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='construction_type_fk',
            field=models.ForeignKey(blank=True, db_column='construction_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_inputs', to='core.constructiontype'),
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='container_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_inputs', to='core.containertype'),
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='cover_grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tds_inputs', to='core.covergrade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=None, on_delete=django.db.models.deletion.PROTECT, related_name='created_tds', to='core.tdsuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_inputs', to='core.customer'),
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='fabric_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_inputs', to='core.fabricstyle'),
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='fabric_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tds_inputs', to='core.fabrictype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='packing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_inputs', to='core.packingtype'),
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='purpose',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tds_inputs', to='core.purpose'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='reel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_inputs', to='core.reeltype'),
        ),
        migrations.AddField(
            model_name='tdsinput',
            name='standard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tds_inputs', to='core.standard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdsinput',
            name='belt_length_m',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tdsinput',
            name='belt_weight_per_m_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tdsinput',
            name='length_per_roll_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tdsinput',
            name='total_extra_length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='beltrating',
            unique_together={('fabric_type', 'rating_name')},
        ),
        migrations.AlterUniqueTogether(
            name='beltratingvalue',
            unique_together={('belt_rating', 'parameter')},
        ),
        migrations.AlterUniqueTogether(
            name='brandbelttype',
            unique_together={('brand', 'belt_type')},
        ),
        migrations.AlterUniqueTogether(
            name='brandparameter',
            unique_together={('brand', 'parameter')},
        ),
        migrations.AlterUniqueTogether(
            name='covergrade',
            unique_together={('standard', 'grade_code')},
        ),
        migrations.AlterUniqueTogether(
            name='covergradevalue',
            unique_together={('cover_grade', 'parameter')},
        ),
        migrations.AlterUniqueTogether(
            name='dimensionalparameterspec',
            unique_together={('standard', 'parameter', 'min_value', 'max_value')},
        ),
        migrations.AlterUniqueTogether(
            name='fabricstyle',
            unique_together={('fabric_type', 'style_name')},
        ),
        migrations.AlterUniqueTogether(
            name='fabricstyleparametervalue',
            unique_together={('fabric_style', 'parameter')},
        ),
        migrations.AlterUniqueTogether(
            name='fabrictypeparametervalue',
            unique_together={('fabric_type', 'parameter')},
        ),
        migrations.AlterUniqueTogether(
            name='purposebelttype',
            unique_together={('purpose', 'belt_type')},
        ),
        migrations.AlterUniqueTogether(
            name='regioncontainerweightlimit',
            unique_together={('region', 'container_type')},
        ),
        migrations.AlterUniqueTogether(
            name='standardtestmethod',
            unique_together={('standard', 'parameter')},
        ),
        migrations.AlterUniqueTogether(
            name='tdsparameter',
            unique_together={('parameter_group', 'parameter_name')},
        ),
    ]
