# Generated by Django 5.2.17 on 2026-08-28 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_trusteddevice_user_tdsbatch_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAPItemSubRow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('characteristic', models.CharField(blank=True)),
                ('check_class', models.CharField(blank=True, max_length=50)),
                ('type_of_check', models.CharField(blank=True)),
                ('quantum_m', models.CharField(blank=True, max_length=200)),
                ('quantum_sc', models.CharField(blank=True, max_length=200)),
                ('reference_docs', models.TextField(blank=True)),
                ('acceptance_norms', models.TextField(blank=True)),
                ('format_of_records', models.CharField(blank=True, max_length=200)),
                ('agency', models.CharField(blank=True, max_length=100)),
                ('record_mark', models.CharField(blank=True, max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_rows_data', to='core.qapitem')),
            ],
            options={
                'db_table': 'qap_item_sub_rows',
                'ordering': ['sort_order'],
                'managed': True,
            },
        ),
    ]
