# Generated by Django 5.2.17 on 2026-08-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_qap_item_sub_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdsinput',
            name='roll_lengths_m',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
