# Generated by Django 5.2.17 on 2026-08-29 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tdsinput_roll_lengths_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdsinput',
            name='current_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TDSRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.TextField(blank=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tdsuser')),
                ('tds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.tdsinput')),
            ],
            options={
                'db_table': 'tds_revisions',
                'ordering': ['-revision_number'],
                'managed': True,
                'unique_together': {('tds', 'revision_number')},
            },
        ),
    ]
