# Generated by Django 5.2.17 on 2026-08-30 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_fix_chk_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchExportJob',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('zip', 'ZIP (per-belt + merged)'), ('merged_zip', 'Merged ZIP'), ('print_all', 'Print-all merged PDF')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_bytes', models.BinaryField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='core.tdsbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tdsuser')),
            ],
            options={
                'db_table': 'batch_export_jobs',
                'managed': True,
            },
        ),
    ]
