# Generated by Django 5.2.17 on 2026-08-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_batch_export_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchexportjob',
            name='progress_current',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchexportjob',
            name='progress_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
