"""
apps/core/migrations/0027_fix_customers_identity_generation.py

Fixes `customers.customer_id` on any database where it was provisioned as a
strict SQL `GENERATED ALWAYS AS IDENTITY` column instead of the permissive
`GENERATED BY DEFAULT` a Django AutoField actually needs.

THE BUG: models.py declares `customer_id = models.AutoField(primary_key=True)`
(see 0001_initial.py's CreateModel), which Django/Postgres normally
implements as `GENERATED BY DEFAULT AS IDENTITY` — permissive, allows an
explicit value to be supplied in an INSERT (which bulk_create() with
explicit PKs relies on — see 0026/0028_backfill_customers.py). But this
project's own local dev `customers` table — provisioned outside Django
originally, like several other tables CLAUDE.md documents this history for
— was created with the STRICT `GENERATED ALWAYS AS IDENTITY` variant, which
rejects any INSERT that supplies its own value at all
(`django.db.utils.ProgrammingError: cannot insert a non-DEFAULT value into
column "customer_id" ... HINT: Use OVERRIDING SYSTEM VALUE to override`) —
found when 0028_backfill_customers.py's bulk_create() was tested against it.

A database built purely from these migrations from scratch (verified: a
genuinely fresh Postgres instance) never has this problem — Django's own
AutoField always produces the permissive variant. So this is specifically a
local-dev-environment schema drift, same root cause as 0024's junction-table
PK fix, fixed the same way: SeparateDatabaseAndState, so the migration STATE
(what Django believes this column is — already correct, matches models.py)
is untouched, and only the DATABASE gets normalized where it's actually
wrong.

IDEMPOTENT BY DESIGN: checks live catalog state and skips any database
that's already GENERATED BY DEFAULT (or not an identity column at all) —
true for a from-scratch deploy — so this is safe to run unconditionally
everywhere.
"""
from django.db import migrations


def fix_identity_generation(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT identity_generation FROM information_schema.columns
            WHERE table_name = 'customers' AND column_name = 'customer_id'
            """
        )
        row = cursor.fetchone()
        current = row[0] if row else None

        if current != 'ALWAYS':
            # Already permissive (or not an identity column at all, e.g. a
            # plain serial/DEFAULT nextval() column) — nothing to do.
            return

        cursor.execute(
            'ALTER TABLE "customers" ALTER COLUMN "customer_id" '
            'SET GENERATED BY DEFAULT'
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_seed_customers'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(fix_identity_generation, noop_reverse),
            ],
            state_operations=[],   # model state is already correct — see docstring
        ),
    ]
