# Generated by Django 5.2.17 on 2026-08-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_backfill_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdsinput',
            name='first_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
