# Generated by Django 5.2.17 on 2026-09-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_tds_first_downloaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdsuser',
            name='signature_content_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tdsuser',
            name='signature_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
