"""
apps/services/otp_service.py — PostgreSQL-backed OTP store with TTL.

Replaces the previous in-memory dict implementation which was not safe for
multi-worker Gunicorn deployments (each worker had its own memory space, so
an OTP generated by worker A would never be found by worker B).

Security design
---------------
- OTP codes are 6-digit strings generated with secrets.randbelow (CSPRNG).
- Only the bcrypt HASH of the code is stored in the DB — never the plaintext.
  Even direct DB access cannot reveal a valid code.
- One active OTP per email: generate_otp() atomically deletes any existing row
  for that email before inserting a new one (prevents accumulation of stale codes).
- expires_at is stored as a timezone-aware UTC datetime, enforced in Python
  before attempting bcrypt verification.
- Attempt counter increments on each wrong guess; at MAX_ATTEMPTS the row is
  deleted (same as before, but now durable across restarts and workers).
- On successful verification the row is deleted immediately (single-use).
- Expired rows for other emails are pruned opportunistically on each generate call.
"""
from __future__ import annotations

import logging
import secrets
from datetime import timedelta

import bcrypt
from django.utils import timezone

log = logging.getLogger(__name__)

_OTP_TTL_MINUTES = 10
_MAX_ATTEMPTS    = 5


# ── Internal helpers ──────────────────────────────────────────────────────────

def _hash_code(code: str) -> str:
    """Return a bcrypt hash of the OTP code (rounds=10 — fast enough for 6-digit codes)."""
    return bcrypt.hashpw(code.encode(), bcrypt.gensalt(rounds=10)).decode()


def _check_code(code: str, hashed: str) -> bool:
    """Constant-time bcrypt comparison — returns True if code matches the hash."""
    try:
        return bcrypt.checkpw(code.encode(), hashed.encode())
    except Exception:
        return False


# ── Public API ────────────────────────────────────────────────────────────────

def generate_otp(email: str) -> str:
    """
    Generate a cryptographically secure 6-digit OTP, persist its hash to the
    DB, and return the plaintext code (which gets emailed to the user).

    Any existing OTP rows for this email are deleted first (one active code
    per address at a time). Expired rows for other addresses are also pruned.
    """
    # Import here to avoid circular import at module load time
    from apps.core.models import OTPCode

    now  = timezone.now()
    code = str(secrets.randbelow(1_000_000)).zfill(6)

    # Purge stale rows opportunistically (keeps the table lean)
    OTPCode.objects.filter(expires_at__lt=now).delete()

    # Delete any existing OTP for this email (enforce one-at-a-time)
    OTPCode.objects.filter(email=email.lower()).delete()

    OTPCode.objects.create(
        email      = email.lower(),
        code_hash  = _hash_code(code),
        expires_at = now + timedelta(minutes=_OTP_TTL_MINUTES),
        attempts   = 0,
        used       = False,
    )

    log.info("OTP generated for %s (expires in %d min)", email, _OTP_TTL_MINUTES)
    return code


def verify_otp(email: str, code: str) -> bool:
    """
    Return True if `code` matches the stored hash for `email` and the OTP
    has not expired, been used, or exceeded the attempt limit.

    On success  → row is deleted (single-use).
    On failure  → attempt counter incremented; row deleted at MAX_ATTEMPTS.
    """
    from apps.core.models import OTPCode

    key = email.strip().lower()

    try:
        entry = OTPCode.objects.get(email=key)
    except OTPCode.DoesNotExist:
        log.debug("verify_otp: no OTP found for %s", key)
        return False

    now = timezone.now()

    # Expired?
    if now > entry.expires_at:
        entry.delete()
        log.debug("verify_otp: OTP expired for %s", key)
        return False

    # Already used?
    if entry.used:
        entry.delete()
        log.warning("verify_otp: replay attempt on used OTP for %s", key)
        return False

    # Increment attempt counter before checking — prevents timing oracle
    entry.attempts += 1

    if entry.attempts > _MAX_ATTEMPTS:
        entry.delete()
        log.warning("verify_otp: too many attempts for %s — OTP invalidated", key)
        return False

    # bcrypt comparison
    if not _check_code(code.strip(), entry.code_hash):
        entry.save(update_fields=['attempts'])
        log.debug("verify_otp: wrong code for %s (attempt %d)", key, entry.attempts)
        return False

    # Success — consume the OTP immediately
    entry.delete()
    log.info("verify_otp: success for %s", key)
    return True


# ── Email sending (unchanged from Phase 1) ────────────────────────────────────

def send_otp_email(to_email: str, otp: str, full_name: str = "") -> None:
    """
    Send OTP via Django's email backend (configured in settings.py).
    Falls back to stdout if SMTP is not configured.
    """
    from django.conf import settings
    from django.core.mail import send_mail
    from apps.services.email_service import render_email

    greeting = f"Hi {full_name}," if full_name else "Hello,"

    html_body, text_body = render_email(
        greeting=greeting,
        body_paragraphs=[
            "You requested a password reset for your TDS System account.",
            "Your one-time password is provided below. It expires in 10 minutes.",
        ],
        highlight_value=otp,
        highlight_label="Your One-Time Password",
        after_highlight_paragraphs=[
            "If you did not request this change, no action is required and your password will remain unchanged.",
        ],
    )

    if not getattr(settings, 'EMAIL_HOST', ''):
        if settings.DEBUG:
            # Dev convenience only: no SMTP configured locally, so surface the
            # OTP in the console instead of failing every login attempt.
            log.warning("SMTP not configured (DEBUG). OTP for %s: %s", to_email, otp)
            print(f"\n{'='*50}\nOTP for {to_email}: {otp}\n{'='*50}\n")
            return
        # SECURITY: never silently degrade OTP delivery to "readable in logs"
        # in production -- an unconfigured mailer must fail the login attempt,
        # not hand out the code to anyone with log access.
        log.error("SMTP not configured and DEBUG=False; refusing to send OTP for %s", to_email)
        raise RuntimeError("Email delivery is not configured on this server.")

    try:
        send_mail(
            subject="Your TDS System Password Reset OTP",
            message=text_body,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[to_email],
            html_message=html_body,
            fail_silently=False,
        )
        log.info("OTP email sent to %s", to_email)
    except Exception as exc:
        log.error("Failed to send OTP email to %s: %s", to_email, exc)
        if settings.DEBUG:
            print(f"\nOTP (email failed, DEBUG) for {to_email}: {otp}\n")
        raise RuntimeError(f"Email delivery failed: {exc}") from exc
