"""
apps/services/otp_service.py — PostgreSQL-backed OTP store with TTL.

Replaces the previous in-memory dict implementation which was not safe for
multi-worker Gunicorn deployments (each worker had its own memory space, so
an OTP generated by worker A would never be found by worker B).

Security design
---------------
- OTP codes are 6-digit strings generated with secrets.randbelow (CSPRNG).
- Only the bcrypt HASH of the code is stored in the DB — never the plaintext.
  Even direct DB access cannot reveal a valid code.
- One active OTP per email: generate_otp() atomically deletes any existing row
  for that email before inserting a new one (prevents accumulation of stale codes).
- expires_at is stored as a timezone-aware UTC datetime, enforced in Python
  before attempting bcrypt verification.
- Attempt counter increments on each wrong guess; at MAX_ATTEMPTS the row is
  deleted (same as before, but now durable across restarts and workers).
- On successful verification the row is deleted immediately (single-use).
- Expired rows for other emails are pruned opportunistically on each generate call.
"""
from __future__ import annotations

import logging
import secrets
from datetime import timedelta

import bcrypt
from django.utils import timezone

log = logging.getLogger(__name__)

_OTP_TTL_MINUTES = 10
_MAX_ATTEMPTS    = 5


# ── Internal helpers ──────────────────────────────────────────────────────────

def _hash_code(code: str) -> str:
    """Return a bcrypt hash of the OTP code (rounds=10 — fast enough for 6-digit codes)."""
    return bcrypt.hashpw(code.encode(), bcrypt.gensalt(rounds=10)).decode()


def _check_code(code: str, hashed: str) -> bool:
    """Constant-time bcrypt comparison — returns True if code matches the hash."""
    try:
        return bcrypt.checkpw(code.encode(), hashed.encode())
    except Exception:
        return False


# ── Public API ────────────────────────────────────────────────────────────────

def generate_otp(email: str) -> str:
    """
    Generate a cryptographically secure 6-digit OTP, persist its hash to the
    DB, and return the plaintext code (which gets emailed to the user).

    Any existing OTP rows for this email are deleted first (one active code
    per address at a time). Expired rows for other addresses are also pruned.
    """
    # Import here to avoid circular import at module load time
    from apps.core.models import OTPCode

    now  = timezone.now()
    code = str(secrets.randbelow(1_000_000)).zfill(6)

    # Purge stale rows opportunistically (keeps the table lean)
    OTPCode.objects.filter(expires_at__lt=now).delete()

    # Delete any existing OTP for this email (enforce one-at-a-time)
    OTPCode.objects.filter(email=email.lower()).delete()

    OTPCode.objects.create(
        email      = email.lower(),
        code_hash  = _hash_code(code),
        expires_at = now + timedelta(minutes=_OTP_TTL_MINUTES),
        attempts   = 0,
        used       = False,
    )

    log.info("OTP generated for %s (expires in %d min)", email, _OTP_TTL_MINUTES)
    return code


def verify_otp(email: str, code: str) -> bool:
    """
    Return True if `code` matches the stored hash for `email` and the OTP
    has not expired, been used, or exceeded the attempt limit.

    On success  → row is deleted (single-use).
    On failure  → attempt counter incremented; row deleted at MAX_ATTEMPTS.
    """
    from apps.core.models import OTPCode

    key = email.strip().lower()

    try:
        entry = OTPCode.objects.get(email=key)
    except OTPCode.DoesNotExist:
        log.debug("verify_otp: no OTP found for %s", key)
        return False

    now = timezone.now()

    # Expired?
    if now > entry.expires_at:
        entry.delete()
        log.debug("verify_otp: OTP expired for %s", key)
        return False

    # Already used?
    if entry.used:
        entry.delete()
        log.warning("verify_otp: replay attempt on used OTP for %s", key)
        return False

    # Increment attempt counter before checking — prevents timing oracle
    entry.attempts += 1

    if entry.attempts > _MAX_ATTEMPTS:
        entry.delete()
        log.warning("verify_otp: too many attempts for %s — OTP invalidated", key)
        return False

    # bcrypt comparison
    if not _check_code(code.strip(), entry.code_hash):
        entry.save(update_fields=['attempts'])
        log.debug("verify_otp: wrong code for %s (attempt %d)", key, entry.attempts)
        return False

    # Success — consume the OTP immediately
    entry.delete()
    log.info("verify_otp: success for %s", key)
    return True


# ── Email sending (unchanged from Phase 1) ────────────────────────────────────

def send_otp_email(to_email: str, otp: str, full_name: str = "") -> None:
    """
    Send OTP via Django's email backend (configured in settings.py).
    Falls back to stdout if SMTP is not configured.
    """
    from django.conf import settings
    from django.core.mail import send_mail

    greeting = f"Hi {full_name}," if full_name else "Hello,"

    html_body = f"""
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8" /></head>
<body style="margin:0;padding:0;background:#F0F2F5;font-family:Inter,Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 0;">
    <tr><td align="center">
      <table width="480" cellpadding="0" cellspacing="0"
             style="background:#fff;border:1px solid #E2E8F0;border-radius:10px;overflow:hidden;">
        <tr>
          <td style="background:#1A2535;padding:24px 32px;border-bottom:3px solid #D4940A;">
            <p style="margin:0;font-family:Montserrat,Arial,sans-serif;font-size:18px;
                      font-weight:900;letter-spacing:.04em;color:#fff;">
              INDUS <span style="color:#F0B429;">TDS</span> SYSTEM
            </p>
            <p style="margin:4px 0 0;font-size:11px;color:rgba(255,255,255,.6);
                      letter-spacing:.08em;text-transform:uppercase;">
              Ravasco Transmission &amp; Packing
            </p>
          </td>
        </tr>
        <tr>
          <td style="padding:32px;">
            <p style="margin:0 0 8px;font-size:14px;color:#1A202C;">{greeting}</p>
            <p style="margin:0 0 24px;font-size:13px;color:#4A5568;line-height:1.6;">
              You requested a password change for your TDS System account.
              Use the code below — it expires in <strong>10 minutes</strong>.
            </p>
            <div style="background:#FEF3C7;border:2px dashed #D4940A;border-radius:8px;
                        padding:20px;text-align:center;margin:0 0 24px;">
              <p style="margin:0 0 4px;font-size:10px;font-weight:700;letter-spacing:.15em;
                        text-transform:uppercase;color:#C17F0A;">Your One-Time Password</p>
              <p style="margin:0;font-family:Courier New,monospace;font-size:36px;
                        font-weight:900;letter-spacing:.25em;color:#1A2535;">{otp}</p>
            </div>
            <p style="margin:0 0 6px;font-size:11px;color:#718096;line-height:1.5;">
              If you did not request this, please ignore this email.
              Your password will remain unchanged.
            </p>
          </td>
        </tr>
        <tr>
          <td style="background:#F7F8FA;padding:16px 32px;border-top:1px solid #E2E8F0;">
            <p style="margin:0;font-size:10px;color:#A0AEC0;text-align:center;">
              ISO 9001:2015 Certified · Internal Use Only
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>"""

    text_body = f"{greeting}\n\nYour TDS System OTP: {otp}\n\nExpires in 10 minutes.\n"

    if not getattr(settings, 'EMAIL_HOST', ''):
        log.warning("SMTP not configured. OTP for %s: %s", to_email, otp)
        print(f"\n{'='*50}\nOTP for {to_email}: {otp}\n{'='*50}\n")
        return

    try:
        send_mail(
            subject="Your TDS System Password Reset OTP",
            message=text_body,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[to_email],
            html_message=html_body,
            fail_silently=False,
        )
        log.info("OTP email sent to %s", to_email)
    except Exception as exc:
        log.error("Failed to send OTP email to %s: %s", to_email, exc)
        print(f"\nOTP (email failed) for {to_email}: {otp}\n")
        raise RuntimeError(f"Email delivery failed: {exc}") from exc
